module.exports = Object.freeze({
    CPU_DES: [
        "core_count",
        "core_clock",
        "boost_clock",
        "tdp",
        "smt",
    ],
    GPU_DES: [
        "name",
        "chipset",
        "memory",
        "core_clock",
        "boost_clock",
        "color",
        "length",
        "rating_count",
    ],
    MOTHERBOARD_DES: [
        "name",
        "socket_/_cpu",
        "form_factor",
        "memory_max",
        "memory_slots",
        "color",
        "rating_count",
    ],
    RAM_DES: [
        "name",
        "speed",
        "modules",
        "price_/_gb",
        "first_word_latency",
        "color",
        "cas_latency",
        "rating_count",
    ],
    STORAGE_DES: [
        "name",
        "capacity",
        "price_/_gb",
        "type",
        "cache",
        "form_factor",
        "interface",
        "rating_count",
    ],
    COOLING_CPU_DES: [
        "name",
        "fan_rpm",
        "noise_level",
        "color",
        "radiator_size",
        "rating_count",
    ],
    POWER_SUPPLY_DES: [
        "name",
        "form_factor",
        "efficiency_rating",
        "wattage",
        "modular",
        "color",
        "rating_count",
    ],
    CASE_DES: [
        "name",
        "type",
        "color",
        "power_supply",
        "side_panel_window",
        "external_5.25\"_bays",
        "internal_3.5\"_bays",
        "rating_count",
    ],
});

